version: '3.1'
services:
  mongo:
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 4
    restart: always
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: mongo
    ports:
      - '27017:27017'
